import localFont from "next/font/local";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import Navbar from "@/components/global/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // console.log(user)
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <>
          <SessionProvider>
            <>
              <Navbar />
              {children}
            </>
          </SessionProvider>
        </>
      </body>
    </html>
  );
}
